version: '3'
services:
  app:
      build: ./docker/app/
      container_name: encard_app
      volumes:
          - ./:/usr/share/nginx/www
          - ./docker/app/php-ini:/usr/local/etc/php/custom.d
      environment:
        PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      working_dir: /usr/share/nginx/www
      depends_on:
        - postgres
  nginx:
      build: ./docker/nginx
      container_name: encard_server
      links:
          - app
      volumes_from:
          - app
      ports:
          - 82:80
  postgres:
    image: postgres:10.1
    container_name: encard_db
    restart: always
    ports:
          - 5432:5432
    environment:
      POSTGRES_DB: encard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  postgres_tests:
    image: postgres:10.1
    container_name: encard_db_test
    restart: always
    ports:
          - 5433:5433
    environment:
      POSTGRES_DB: encard_test
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: tester
    volumes:
      - ./postgres_test/data:/var/lib/postgresql/data
  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  chrome:
    container_name: chrome
    image: browserless/chrome
    ports:
      - 3000:3000
    
