version: '3'
services:
  app:
      build: ./docker/app/
      container_name: encard_app
      volumes:
          - ./:/usr/share/nginx/www
      working_dir: /usr/share/nginx/www
      depends_on:
        - postgres
  nginx:
      build: ./docker/nginx
      container_name: encard_server
      links:
          - app
      volumes_from:
          - app
      ports:
          - 80:80
  postgres:
    image: postgres:10.1
    container_name: encard_db
    restart: always
    ports:
          - 5432:5432
    environment:
      POSTGRES_DB: ejournal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    
  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
